'use strict';

import {
  isProblemExistAvailable,
  registerNewType,
  getTypeInfoById,
  getAllTypeInfo,
  updateTypeInfoById,
  isTagExist,
  registerNewTagInfo,
  getTagInfoById,
  getTags,
  updateTagInfo,
  deleteProblemTypeInfoById,
  deleteTagInfoById,
  isLanguageExistAvailable,
  registerNewLanguage,
  getLangInfoById,
  getAllLanguages,
  updateLanguageInfo,
  deleteLanguageInfo,
  isProblemExist,
  getMultipleTagsByIds,
  getMultipleLanguagesByIds,
  getLastProblemCode,
  getProblemInfoById,
  getProblemTagsById,
  getProblemExampleById,
  getProblemHintById,
  getProblemTestCasesById,
  getProblemSnippetsById,
} from './problem.db.js';

import { saveProblemRecords } from './problemTrans.db.js';

export {
  isProblemExistAvailable,
  registerNewType,
  getTypeInfoById,
  getAllTypeInfo,
  updateTypeInfoById,
  isTagExist,
  registerNewTagInfo,
  getTagInfoById,
  getTags,
  updateTagInfo,
  deleteProblemTypeInfoById,
  deleteTagInfoById,
  isLanguageExistAvailable,
  registerNewLanguage,
  getLangInfoById,
  getAllLanguages,
  updateLanguageInfo,
  deleteLanguageInfo,
  isProblemExist,
  getMultipleTagsByIds,
  getMultipleLanguagesByIds,
  getLastProblemCode,
  getProblemInfoById,
  getProblemTagsById,
  getProblemExampleById,
  getProblemHintById,
  getProblemTestCasesById,
  getProblemSnippetsById,
  saveProblemRecords,
};
